SEARCHBOX_LOCATOR="twotabsearchtextbox"
SEARCHBOX_BUTTON_LOCATOR="nav-search-submit-button"
FIRST_PRODUCT_LOCATOR="[data-index='0']"
FIRST_ITEM_NAME_LOCATOR = "/html/body/div[2]/div/div[7]/div[3]/div[4]/div[1]/div/h1/span"
STANDART_PACKAGE_LOCATOR ="/html/body/div[2]/div/div[7]/div[3]/div[1]/div[3]/div/div[1]/div/div[1]/div/div/div[2]/div/div[1]"
ADD_CART_BUTTON_LOCATOR="add-to-cart-button"
ADD_PRODUCT_ASSERT_LOCATOR="//*[@id='NATC_SMART_WAGON_CONF_MSG_SUCCESS']/h1"
GO_TO_CART_BUTTON_LOCATOR = "//*[@id='ewc-compact-actions-container']/div/div[1]/span/span/a"
DELETE_BUTTON_LOCATOR = "/html/body/div[1]/header/div/div[7]/div[1]/div/div/div[4]/div/div/div[2]/div[3]/div[7]/div[2]/div/span/span"
EMPTY_BASKET_LOCATOR =  "/html/body/div[1]/div[1]/div[3]/div[4]/div/div[2]/div[1]/div/div/div[2]/div[1]"
GO_TO_BASKET_LOCATOR ="//*[@id='sw-gtc']/span"
MULTI_ASSERT_TEXT_LOCATOR = "//*[@id='sc-subtotal-label-activecart']"
