CLICK_LOGIN_BUTTON_LOCATOR ="//a[@id='nav-link-accountList']/span"
EMAIL_INPUT_LOCATOR="ap_email"
CLICK_CONTINUE_BUTTON_LOCATOR ="continue"
PASSWORD_INPUT_LOCATOR="ap_password"
LOGIN_BUTTON_LOCATOR ="signInSubmit"
LOGIN_SUCCESS_ALERT_MESSAGE = "nav-link-accountList-nav-line-1"
EMAIL_NOT_FOUND_ALERT_MESSAGE = "//div[@class='a-alert-content']"
WRONG_PASSWORD_ALERT_MESSAGE = "//div[@class='a-alert-content']"
REQUIRED_AREA_EMAIL_ALERT_MESSAGE = "auth-email-missing-alert"
REQUIRED_AREA_PASSWORD_ALERT_MESSAGE = "auth-password-missing-alert"

registeredEmail ="denemehesabi299@outlook.com"
registeredPassword ="159753QA"