SEARCHBOX_LOCATOR="twotabsearchtextbox"
SEARCHBOX_BUTTON_LOCATOR="nav-search-submit-button"
FIRST_PRODUCT_LOCATOR="[data-index='0']"
FIRST_ITEM_NAME_LOCATOR = "/html/body/div[4]/div/div[3]/div[10]/div[3]/div/h1/span"
RATING_LOCATOR ="//*[@id='acrPopover']/span[1]/a/i[1]"
RATING_TOTA_LOCATOR = "acrCustomerReviewText"
REVIEWS_LOCATOR = "//*[@id='cm-cr-local-reviews-title']/h3"